railsTest/config/routes.rb
Rails.application.routes.draw do
  get 'article/index'
  get 'users/new'

  get "log_in" => "users#login", :as => "log_in"
  get "my_account" => "users#my_account", :as => "my_account"
  get "log_out" => "users#logout", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  get 'edit' => 'users#edit'
  root :to => "welcome#index"

  resources :users do
    post 'process_login', :on => :collection
  end

  resources :articles do
    resources :comments
    member do
      post 'upvote'
    end
  end

end

railsTest/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  mount_uploader :picture, ImageUploader
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

railsTest/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

railsTest/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_many :posts
  has_many :comments
  has_many :articles
  mount_uploader :profile_pic, ImageUploader

  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
      user
    else
      nil
    end
  end
end

railsTest/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :article
end

railsTest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  config.time_zone = 'Tokyo'

  protected
  def login_required
    return true if User.find_by_id(session[:user_id])
    access_denied
    return false
  end

  def access_denied
    flash[:error] = 'Oops. You need to login before you can view that page.'
    redirect_to :log_in
  end
end

railsTest/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
    @articles = Article.page(params[:articles]).per(8).order("title")
    @profile_pic = User.find(session[:user_id]).profile_pic
    if session[:user_id] != nil
      @sessName = User.find(session[:user_id]).firstname
    else
      @sessName = "Guest"
    end
  end

  def upvote
    @article = Article.find(params[:id])
    @article.votes.create
    redirect_to (root_path)
  end

  def show
    @user = User.all
    @article = Article.find(params[:id]).picture
    @profile_pic = User.find(session[:user_id]).profile_pic
    @article = Article.find(params[:id])
    if session[:user_id] != nil
      @sessName = User.find(session[:user_id]).firstname
    else
      @sessName = "Guest"
    end
  end

  def new
    @article = Article.new
    @profile_pic = User.find(session[:user_id]).profile_pic
    if session[:user_id] != nil
      @sessName = User.find(session[:user_id]).firstname
    else
      @sessName = "Guest"
    end
  end

  def edit
    @article = Article.find(params[:id])
    @profile_pic = User.find(session[:user_id]).profile_pic
    if session[:user_id] != nil
      @sessName = User.find(session[:user_id]).firstname
    else
      @sessName = "Guest"
    end
  end

  def create
    @article = Article.new(article_params)
    @profile_pic = User.find(session[:user_id]).profile_pic

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end


  private
  def article_params
    params.require(:article).permit(:title, :text, :picture)
  end
end

railsTest/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
    end
end

railsTest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :log_in, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def edit
    @profile_pic = User.find(session[:user_id]).profile_pic
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to :articles
    else
      render 'edit'
    end
  end

  def login
  end

  def process_login
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to :articles, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "login"
    end
  end

  def my_account
    @profile_pic = User.find(session[:user_id]).profile_pic
  end

  def logout
    session[:user_id] = nil
    redirect_to :log_in, :notice => "Logged out!"
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :profile_pic)
  end
end

railsTest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
    @articles = Article.page(params[:articles]).per(8).order("title")
  end

  def show
    @user = User.all
    @article = Article.find(params[:id]).picture
    @article = Article.find(params[:id])
  end
end

railsTest/app/helpers/application_helper.rb
module ApplicationHelper
end

railsTest/app/helpers/articles_helper.rb
module ArticlesHelper
  def paginate objects, options = {}
    options.reverse_merge!( theme: 'twitter-bootstrap-3' )

    super( objects, options )
  end
end

railsTest/app/helpers/comments_helper.rb
module CommentsHelper
end

railsTest/app/helpers/posts_helper.rb
module PostsHelper
end

railsTest/app/helpers/users_helper.rb
module UsersHelper
end

railsTest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

railsTest/app/views/articles/_header.html.erb
<!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-dynamic-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-toggle"></span>
      </button>
      <a class="navbar-brand" href="#">For Him Magazine</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
            <%= image_tag @profile_pic, :class => 'img-circle img-avatar'%>&nbsp;&nbsp;<%= @sessName %> <span class="caret"></span></a>
          <ul id="g-account-menu" class="dropdown-menu" role="menu">
            <li><%= link_to 'New article', new_article_path %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><a href="log_out"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

railsTest/app/views/articles/edit.html.erb
<%= render 'articles/header'%>
<div class="container wew">
<h1>Editing article</h1>
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <h1>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </h1>
    <h1>
      <%= f.label :Description %><br>
      <%= f.text_area :text %>
    </h1><br><br>
      <%= f.label :picture %><br>
      <%= f.file_field :picture %>
    <h1>
      <%= f.submit %>
    </h1>
<% end %>
<%= link_to 'Back', articles_path,:class=>'btn btn-primary' %>
</div>

railsTest/app/views/articles/index.html.erb
<%= render 'articles/header' %>
<div class="container wew">
  <h1>Listing articles</h1>
  <div class="list-article">
     <h4><%= page_entries_info @articles %>s</h4>
      <div class="row">
        <% @articles.each do |article| %>
            <div class="col-sm-6 col-md-3">
              <div class="thumbnail user-pic">
                <div class="articles-image-holder">
                  <%= image_tag article.picture, :class=>'image img-responsive col-md-12' %>
                </div>
                <div class="caption">
                  <h3><%= article.title %></h3>
                  <p>Description:<%= article.text %></p>
                  <p class="admin-button"><%= link_to 'Show', article_path(article),:class=>'btn btn-success' %>
                    <%= link_to 'Edit', edit_article_path(article),:class=>'btn btn-info' %>
                    <%= link_to 'Destroy', article_path(article),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },:class=>'btn btn-danger  ' %></p>
                </div>
              </div>
            </div>
        <% end %>
      </div>
      <%= paginate @articles , :param_name => "articles", :theme => 'twitter-bootstrap-3',
                   :pagination_class => 'pagination-small pagination-centered pull-right'%>
  </div>
</div>

railsTest/app/views/articles/new.html.erb
<%= render 'articles/header'%>
<div class="container wew">
  <h1>Add new article</h1>
    <%= form_for :article, url: articles_path do |f| %>
        <h1>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </h1>
        <h2>
          <%= f.label :Description %><br>
          <%= f.text_area :text %>
        </h2>
        <h3>
        <%= f.label :Picture %><br>
        <%= f.file_field :picture %>
        </h3>
        <h4>
          <%= f.submit %>
        </h4>
    <% end %>

<%= link_to 'Back', articles_path, :class => 'btn btn-primary' %>
</div>

railsTest/app/views/articles/show.html.erb
<%= render 'articles/header'%>
<div class="container wew">
  <h1>Show</h1>
  <div class="show col-md-5">
        <h2>
          <strong>Picture:</strong>
        </h2>
          <%= image_tag @article.picture, :class => 'img-thumbnail' %>

        <h2>
          <strong>Title:</strong>
          <%= @article.title %>
        </h2>
        <h2>
          <strong>Description:</strong>
          <%= @article.text %>
        </h2>
   </div>
  <div class=" col-md-5">
    <h4>Comments</h4>
    <div class="display-comment">
       <%= render @article.comments %>
    </div>
  <h4>Add a comment:</h4>
     <%= render 'comments/form' %>
    <%= link_to 'Back', articles_path, :class => 'btn btn-primary' %> |
    <%= link_to 'Edit', edit_article_path(@article), :class => 'btn btn-primary' %>
  </div>
 </div>

railsTest/app/views/comments/_comment.html.erb
<div class="comment">
    <%= link_to 'X', [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' },:class => 'pull-right' %>
    <% @article.comments.each do |comment| %>
            <h4>
              <strong><%= comment.commenter %>:</strong>
                <%= comment.body %>
            </h4>
    <% end %>
</div>

railsTest/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body ,:class=> 'col-md-8' %>
    </p>
    <br><br><br><br>
    <p>
      <%= f.submit %>
    </p>
<% end %>

railsTest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

railsTest/app/views/users/edit.html.erb
<div class="container wew">
  <div class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="panel-title">Update Profile</div>
      </div>
      <div class="panel-body form-horizontal" >
        <%= form_for @user do |f| %>
            <% if @user.errors.any? %>
                <div class="alert alert-danger">
                  <h2>Form is invalid</h2>
                  <ul>
                    <% for message in @user.errors.full_messages %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <div class="form-group">
              <div class="col-md-12 edit-image-holder">
                  <%= image_tag @profile_pic, :class => 'image col-md-8'%>
              </div>
            </div>
            <div class="form-group">
              <label for="email" class="col-md-3 control-label">Email</label>
              <div class="col-md-9">
                <%= f.text_field :email, :class=>'form-control', :placeholder=>'Email'%>
              </div>
            </div>
            <div class="form-group">
              <label for="firstname" class="col-md-3 control-label">Firstname</label>
              <div class="col-md-9">
                <%= f.text_field :firstname, :class=>'form-control', :placeholder=>'Firstname'%>
              </div>
            </div>
            <div class="form-group">
              <label for="lastname" class="col-md-3 control-label">Lastname</label>
              <div class="col-md-9">
                <%= f.text_field :lastname, :class=>'form-control', :placeholder=>'Lastname'%>
              </div>
            </div>
            <div class="form-group">
              <label for="password" class="col-md-3 control-label">Password</label>
              <div class="col-md-9">
                <%= f.password_field :password, :class=>'form-control', :placeholder=>'Password'%>
              </div>
            </div>
            <div class="form-group">
              <label for="Confirm-password" class="col-md-3 control-label">Confirm password</label>
              <div class="col-md-9">
                <%= f.password_field :password_confirmation, :class=>'form-control', :placeholder=>'Confirm password'%>
              </div>
            </div>
            <div class="form-group">
              <%= f.label 'Profile Picture', :class => 'text-align-left col-md-3 control-label' %>
              <div class="col-lg-8">
                <%= f.file_field :profile_pic, :class => 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <!-- Button -->
              <div class="col-md-offset-3 col-md-9">
                <p><%= submit_tag "Submit", :class => 'btn btn-info' %> || <%= link_to "Back", articles_path(current_user) %></p>

              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

railsTest/app/views/users/login.html.erb
<div class="container">
  <div id="loginbox" class="login mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="panel-title">Sign In</div>
        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
      </div>

      <div style="padding-top:30px" class="panel-body">
        <%= form_tag :action => 'process_login' %>

        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

        <form id="loginform" class="form-horizontal" role="form">

          <div style="margin-bottom: 25px" class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= text_field_tag :email, params[:email], :class => 'form-control', :placeholder=>'Email Address' %>
          </div>

          <div style="margin-bottom: 25px" class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <%= text_field_tag :password, params[:password], :type => 'password', :class => 'form-control',:placeholder=>'Password' %>
          </div>


          <div class="input-group">
            <div class="checkbox">
              <label>
                <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
              </label>
            </div>
          </div>
          <div style="margin-top:10px" class="form-group">
            <!-- Button -->
            <div class="col-sm-12 controls">
              <%= submit_tag "Login", :class => 'btn btn-success' %>
              <%= link_to 'Sign-up', users_new_path , :class=> 'btn btn-primary' %>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

railsTest/app/views/users/my_account.html.erb
<div class="container">
  <h1>User Info</h1>
    <div class=" pull-right">
        <a href="log_out" class="btn btn-primary">Logout</a></li>
    </div>
  <div class="content col-md-12 well">
    <div class="col-md-12 ">
      <div class="col-lg-2 profile-pic well">
        <%= image_tag @profile_pic , :class => 'img-thumbnail' %>
         <h4><b><%= @sessName %></b></h4>
      </div>
    </div>
  </div>
</div>

railsTest/app/views/users/new.html.erb
<div class="container">
    <div class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">Sign Up</div>
          <div style="float:right; font-size: 85%; position: relative; top:-10px"><%= link_to 'Sign-in' , :log_in %></div>
        </div>
        <div class="panel-body form-horizontal" >
          <%= form_for @user do |f| %>
              <% if @user.errors.any? %>
                  <div class="alert alert-danger">
                    <h2>Form is invalid</h2>
                    <ul>
                      <% for message in @user.errors.full_messages %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <div class="form-group">
                <label for="email" class="col-md-3 control-label">Email</label>
                <div class="col-md-9">
                  <%= f.text_field :email, :class=>'form-control', :placeholder=>'Email'%>
                </div>
              </div>
              <div class="form-group">
                <label for="firstname" class="col-md-3 control-label">Firstname</label>
                <div class="col-md-9">
                  <%= f.text_field :firstname, :class=>'form-control', :placeholder=>'Firstname'%>
                </div>
              </div>
              <div class="form-group">
                <label for="lastname" class="col-md-3 control-label">Lastname</label>
                <div class="col-md-9">
                  <%= f.text_field :lastname, :class=>'form-control', :placeholder=>'Lastname'%>
                </div>
              </div>
            <div class="form-group">
              <label for="password" class="col-md-3 control-label">Password</label>
              <div class="col-md-9">
                <%= f.password_field :password, :class=>'form-control', :placeholder=>'Password'%>
              </div>
            </div>
            <div class="form-group">
              <label for="Confirm-password" class="col-md-3 control-label">Confirm password</label>
              <div class="col-md-9">
                <%= f.password_field :password_confirmation, :class=>'form-control', :placeholder=>'Confirm password'%>
              </div>
            </div>
            <div class="form-group">
                <%= f.label 'Profile Picture', :class => 'text-align-left col-md-3 control-label' %>
                <div class="col-lg-8">
                  <%= f.file_field :profile_pic, :class => 'form-control' %>
                </div>
              </div>
            <div class="form-group">
              <!-- Button -->
              <div class="col-md-offset-3 col-md-9">
                <p><%= submit_tag "Sign-up", :class => 'btn btn-info' %></p>
              </div>
            </div>
            <% end %>
        </div>
      </div>
   </div>
</div>

railsTest/app/views/welcome/index.html.erb
<div class="container wew">
  <h2>All articles</h2><h4><%= page_entries_info @articles %>s</h4>
      <div class="row">
        <% @articles.each do |article| %>
          <div class="col-sm-6 col-md-3">
            <div class="thumbnail user-pic">
              <div class="articles-image-holder">
                <%= image_tag article.picture, :class=>'image img-responsive col-md-12' %>
              </div>
              <div class="caption">
                <h3><%= article.title %></h3>
                <p>Description:<%= article.text %></p>
                <%= pluralize(article.votes.count, "vote") %>
                <p><%= button_to 'Vote +1', upvote_article_path(article), :class=> 'btn btn-primary', method: :post %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <%= paginate @articles , :param_name => "articles", :theme => 'twitter-bootstrap-3',
               :pagination_class => 'pagination-small pagination-centered pull-right'%>
</div>